// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: publication.proto
// Protobuf Java Version: 4.28.3

package project.proto;

public final class Pubsub {
  private Pubsub() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Pubsub.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:project.proto.Publication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pub_id = 1;</code>
     * @return The pubId.
     */
    java.lang.String getPubId();
    /**
     * <code>string pub_id = 1;</code>
     * @return The bytes for pubId.
     */
    com.google.protobuf.ByteString
        getPubIdBytes();

    /**
     * <code>int64 emit_timestamp_ms = 2;</code>
     * @return The emitTimestampMs.
     */
    long getEmitTimestampMs();

    /**
     * <code>int32 hop_count = 3;</code>
     * @return The hopCount.
     */
    int getHopCount();

    /**
     * <code>string company = 4;</code>
     * @return The company.
     */
    java.lang.String getCompany();
    /**
     * <code>string company = 4;</code>
     * @return The bytes for company.
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>double value = 5;</code>
     * @return The value.
     */
    double getValue();

    /**
     * <code>double drop = 6;</code>
     * @return The drop.
     */
    double getDrop();

    /**
     * <code>double variation = 7;</code>
     * @return The variation.
     */
    double getVariation();

    /**
     * <code>string date = 8;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 8;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * <pre>
   * Mesaj binar pentru publicatiile transmise de la publisher la brokeri.
   * Doar acest mesaj este serializat binar (Protocol Buffers); celelalte
   * mesaje ale sistemului (SUB, ADV, NOT, precum si PUB-urile forwardate
   * intre brokeri) raman in formatul text linie-cu-linie original.
   * </pre>
   *
   * Protobuf type {@code project.proto.Publication}
   */
  public static final class Publication extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:project.proto.Publication)
      PublicationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Publication.class.getName());
    }
    // Use Publication.newBuilder() to construct.
    private Publication(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Publication() {
      pubId_ = "";
      company_ = "";
      date_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project.proto.Pubsub.internal_static_project_proto_Publication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project.proto.Pubsub.internal_static_project_proto_Publication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project.proto.Pubsub.Publication.class, project.proto.Pubsub.Publication.Builder.class);
    }

    public static final int PUB_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object pubId_ = "";
    /**
     * <code>string pub_id = 1;</code>
     * @return The pubId.
     */
    @java.lang.Override
    public java.lang.String getPubId() {
      java.lang.Object ref = pubId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pubId_ = s;
        return s;
      }
    }
    /**
     * <code>string pub_id = 1;</code>
     * @return The bytes for pubId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPubIdBytes() {
      java.lang.Object ref = pubId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMIT_TIMESTAMP_MS_FIELD_NUMBER = 2;
    private long emitTimestampMs_ = 0L;
    /**
     * <code>int64 emit_timestamp_ms = 2;</code>
     * @return The emitTimestampMs.
     */
    @java.lang.Override
    public long getEmitTimestampMs() {
      return emitTimestampMs_;
    }

    public static final int HOP_COUNT_FIELD_NUMBER = 3;
    private int hopCount_ = 0;
    /**
     * <code>int32 hop_count = 3;</code>
     * @return The hopCount.
     */
    @java.lang.Override
    public int getHopCount() {
      return hopCount_;
    }

    public static final int COMPANY_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object company_ = "";
    /**
     * <code>string company = 4;</code>
     * @return The company.
     */
    @java.lang.Override
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        company_ = s;
        return s;
      }
    }
    /**
     * <code>string company = 4;</code>
     * @return The bytes for company.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private double value_ = 0D;
    /**
     * <code>double value = 5;</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }

    public static final int DROP_FIELD_NUMBER = 6;
    private double drop_ = 0D;
    /**
     * <code>double drop = 6;</code>
     * @return The drop.
     */
    @java.lang.Override
    public double getDrop() {
      return drop_;
    }

    public static final int VARIATION_FIELD_NUMBER = 7;
    private double variation_ = 0D;
    /**
     * <code>double variation = 7;</code>
     * @return The variation.
     */
    @java.lang.Override
    public double getVariation() {
      return variation_;
    }

    public static final int DATE_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object date_ = "";
    /**
     * <code>string date = 8;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 8;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pubId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, pubId_);
      }
      if (emitTimestampMs_ != 0L) {
        output.writeInt64(2, emitTimestampMs_);
      }
      if (hopCount_ != 0) {
        output.writeInt32(3, hopCount_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(company_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, company_);
      }
      if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
        output.writeDouble(5, value_);
      }
      if (java.lang.Double.doubleToRawLongBits(drop_) != 0) {
        output.writeDouble(6, drop_);
      }
      if (java.lang.Double.doubleToRawLongBits(variation_) != 0) {
        output.writeDouble(7, variation_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, date_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pubId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, pubId_);
      }
      if (emitTimestampMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, emitTimestampMs_);
      }
      if (hopCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, hopCount_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(company_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, company_);
      }
      if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, value_);
      }
      if (java.lang.Double.doubleToRawLongBits(drop_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, drop_);
      }
      if (java.lang.Double.doubleToRawLongBits(variation_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, variation_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, date_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof project.proto.Pubsub.Publication)) {
        return super.equals(obj);
      }
      project.proto.Pubsub.Publication other = (project.proto.Pubsub.Publication) obj;

      if (!getPubId()
          .equals(other.getPubId())) return false;
      if (getEmitTimestampMs()
          != other.getEmitTimestampMs()) return false;
      if (getHopCount()
          != other.getHopCount()) return false;
      if (!getCompany()
          .equals(other.getCompany())) return false;
      if (java.lang.Double.doubleToLongBits(getValue())
          != java.lang.Double.doubleToLongBits(
              other.getValue())) return false;
      if (java.lang.Double.doubleToLongBits(getDrop())
          != java.lang.Double.doubleToLongBits(
              other.getDrop())) return false;
      if (java.lang.Double.doubleToLongBits(getVariation())
          != java.lang.Double.doubleToLongBits(
              other.getVariation())) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUB_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPubId().hashCode();
      hash = (37 * hash) + EMIT_TIMESTAMP_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEmitTimestampMs());
      hash = (37 * hash) + HOP_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getHopCount();
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue()));
      hash = (37 * hash) + DROP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDrop()));
      hash = (37 * hash) + VARIATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVariation()));
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static project.proto.Pubsub.Publication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project.proto.Pubsub.Publication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project.proto.Pubsub.Publication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project.proto.Pubsub.Publication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project.proto.Pubsub.Publication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project.proto.Pubsub.Publication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project.proto.Pubsub.Publication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static project.proto.Pubsub.Publication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static project.proto.Pubsub.Publication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static project.proto.Pubsub.Publication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static project.proto.Pubsub.Publication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static project.proto.Pubsub.Publication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(project.proto.Pubsub.Publication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Mesaj binar pentru publicatiile transmise de la publisher la brokeri.
     * Doar acest mesaj este serializat binar (Protocol Buffers); celelalte
     * mesaje ale sistemului (SUB, ADV, NOT, precum si PUB-urile forwardate
     * intre brokeri) raman in formatul text linie-cu-linie original.
     * </pre>
     *
     * Protobuf type {@code project.proto.Publication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:project.proto.Publication)
        project.proto.Pubsub.PublicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project.proto.Pubsub.internal_static_project_proto_Publication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project.proto.Pubsub.internal_static_project_proto_Publication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project.proto.Pubsub.Publication.class, project.proto.Pubsub.Publication.Builder.class);
      }

      // Construct using project.proto.Pubsub.Publication.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        pubId_ = "";
        emitTimestampMs_ = 0L;
        hopCount_ = 0;
        company_ = "";
        value_ = 0D;
        drop_ = 0D;
        variation_ = 0D;
        date_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project.proto.Pubsub.internal_static_project_proto_Publication_descriptor;
      }

      @java.lang.Override
      public project.proto.Pubsub.Publication getDefaultInstanceForType() {
        return project.proto.Pubsub.Publication.getDefaultInstance();
      }

      @java.lang.Override
      public project.proto.Pubsub.Publication build() {
        project.proto.Pubsub.Publication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public project.proto.Pubsub.Publication buildPartial() {
        project.proto.Pubsub.Publication result = new project.proto.Pubsub.Publication(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(project.proto.Pubsub.Publication result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.pubId_ = pubId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.emitTimestampMs_ = emitTimestampMs_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.hopCount_ = hopCount_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.company_ = company_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.drop_ = drop_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.variation_ = variation_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.date_ = date_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project.proto.Pubsub.Publication) {
          return mergeFrom((project.proto.Pubsub.Publication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project.proto.Pubsub.Publication other) {
        if (other == project.proto.Pubsub.Publication.getDefaultInstance()) return this;
        if (!other.getPubId().isEmpty()) {
          pubId_ = other.pubId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getEmitTimestampMs() != 0L) {
          setEmitTimestampMs(other.getEmitTimestampMs());
        }
        if (other.getHopCount() != 0) {
          setHopCount(other.getHopCount());
        }
        if (!other.getCompany().isEmpty()) {
          company_ = other.company_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        if (other.getDrop() != 0D) {
          setDrop(other.getDrop());
        }
        if (other.getVariation() != 0D) {
          setVariation(other.getVariation());
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                pubId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                emitTimestampMs_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                hopCount_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                company_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 41: {
                value_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 49: {
                drop_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              case 57: {
                variation_ = input.readDouble();
                bitField0_ |= 0x00000040;
                break;
              } // case 57
              case 66: {
                date_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object pubId_ = "";
      /**
       * <code>string pub_id = 1;</code>
       * @return The pubId.
       */
      public java.lang.String getPubId() {
        java.lang.Object ref = pubId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pubId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pub_id = 1;</code>
       * @return The bytes for pubId.
       */
      public com.google.protobuf.ByteString
          getPubIdBytes() {
        java.lang.Object ref = pubId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pub_id = 1;</code>
       * @param value The pubId to set.
       * @return This builder for chaining.
       */
      public Builder setPubId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        pubId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string pub_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPubId() {
        pubId_ = getDefaultInstance().getPubId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string pub_id = 1;</code>
       * @param value The bytes for pubId to set.
       * @return This builder for chaining.
       */
      public Builder setPubIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        pubId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long emitTimestampMs_ ;
      /**
       * <code>int64 emit_timestamp_ms = 2;</code>
       * @return The emitTimestampMs.
       */
      @java.lang.Override
      public long getEmitTimestampMs() {
        return emitTimestampMs_;
      }
      /**
       * <code>int64 emit_timestamp_ms = 2;</code>
       * @param value The emitTimestampMs to set.
       * @return This builder for chaining.
       */
      public Builder setEmitTimestampMs(long value) {

        emitTimestampMs_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 emit_timestamp_ms = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmitTimestampMs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        emitTimestampMs_ = 0L;
        onChanged();
        return this;
      }

      private int hopCount_ ;
      /**
       * <code>int32 hop_count = 3;</code>
       * @return The hopCount.
       */
      @java.lang.Override
      public int getHopCount() {
        return hopCount_;
      }
      /**
       * <code>int32 hop_count = 3;</code>
       * @param value The hopCount to set.
       * @return This builder for chaining.
       */
      public Builder setHopCount(int value) {

        hopCount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hop_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHopCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hopCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object company_ = "";
      /**
       * <code>string company = 4;</code>
       * @return The company.
       */
      public java.lang.String getCompany() {
        java.lang.Object ref = company_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          company_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string company = 4;</code>
       * @return The bytes for company.
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        java.lang.Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string company = 4;</code>
       * @param value The company to set.
       * @return This builder for chaining.
       */
      public Builder setCompany(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        company_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string company = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompany() {
        company_ = getDefaultInstance().getCompany();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string company = 4;</code>
       * @param value The bytes for company to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        company_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>double value = 5;</code>
       * @return The value.
       */
      @java.lang.Override
      public double getValue() {
        return value_;
      }
      /**
       * <code>double value = 5;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(double value) {

        value_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = 0D;
        onChanged();
        return this;
      }

      private double drop_ ;
      /**
       * <code>double drop = 6;</code>
       * @return The drop.
       */
      @java.lang.Override
      public double getDrop() {
        return drop_;
      }
      /**
       * <code>double drop = 6;</code>
       * @param value The drop to set.
       * @return This builder for chaining.
       */
      public Builder setDrop(double value) {

        drop_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double drop = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDrop() {
        bitField0_ = (bitField0_ & ~0x00000020);
        drop_ = 0D;
        onChanged();
        return this;
      }

      private double variation_ ;
      /**
       * <code>double variation = 7;</code>
       * @return The variation.
       */
      @java.lang.Override
      public double getVariation() {
        return variation_;
      }
      /**
       * <code>double variation = 7;</code>
       * @param value The variation to set.
       * @return This builder for chaining.
       */
      public Builder setVariation(double value) {

        variation_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>double variation = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearVariation() {
        bitField0_ = (bitField0_ & ~0x00000040);
        variation_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 8;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 8;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 8;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        date_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        date_ = getDefaultInstance().getDate();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string date = 8;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        date_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:project.proto.Publication)
    }

    // @@protoc_insertion_point(class_scope:project.proto.Publication)
    private static final project.proto.Pubsub.Publication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new project.proto.Pubsub.Publication();
    }

    public static project.proto.Pubsub.Publication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Publication>
        PARSER = new com.google.protobuf.AbstractParser<Publication>() {
      @java.lang.Override
      public Publication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Publication> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Publication> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public project.proto.Pubsub.Publication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_project_proto_Publication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_project_proto_Publication_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021publication.proto\022\rproject.proto\"\232\001\n\013P" +
      "ublication\022\016\n\006pub_id\030\001 \001(\t\022\031\n\021emit_times" +
      "tamp_ms\030\002 \001(\003\022\021\n\thop_count\030\003 \001(\005\022\017\n\007comp" +
      "any\030\004 \001(\t\022\r\n\005value\030\005 \001(\001\022\014\n\004drop\030\006 \001(\001\022\021" +
      "\n\tvariation\030\007 \001(\001\022\014\n\004date\030\010 \001(\tB\027\n\rproje" +
      "ct.protoB\006Pubsubb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_project_proto_Publication_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_project_proto_Publication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_project_proto_Publication_descriptor,
        new java.lang.String[] { "PubId", "EmitTimestampMs", "HopCount", "Company", "Value", "Drop", "Variation", "Date", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
